import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#fff',
  },
  header: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    marginBottom: 8,
  },
  headerText: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#333',
  },
  productItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    flexWrap: 'wrap',
  },
  productName: {
    fontSize: 16,
    fontWeight: 'bold',
    flexShrink: 1,
    maxWidth: '85%',
  },
  productDetails: {
    fontSize: 14,
    color: '#555',
    flexShrink: 1,
    maxWidth: '85%',
  },
  removeButton: {
    padding: 8,
    alignSelf: 'flex-start',
    minWidth: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  totalsContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#ccc',
  },
  totalsText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  floatingButton: {
    position: 'absolute',
    right: 10,
    bottom: 20,
    backgroundColor: '#11D9EF',
    width: 160,
    height: 70,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    borderWidth: 1,
  },
  floatingButtonText: {
    fontSize: 18,
    color: '#000',
    fontWeight: 'bold',
    marginBottom: 5,
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 20,
    width: '90%',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  modalTitle2: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 5,
    textAlign: 'center',
  },
  tabSwitchContainer: {
    flexDirection: 'row',
    width: '100%',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 10,
    overflow: 'hidden',
    marginVertical: 10,
    height: 50,
  },
  tabSwitchButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 5,
  },
  tabSwitchButtonActive: {
    backgroundColor: '#11D9EF',
  },
  tabSwitchButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  tabSwitchDivider: {
    width: 1,
    backgroundColor: '#000',
    height: '100%',
  },

  input: {
    width: '100%',
    padding: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    marginBottom: 10,
  },
  switchContainer: {
    flexDirection: 'row',
    width: '100%',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 10,
    overflow: 'hidden',
    marginVertical: 10,
  },
  switchButton: {
    flex: 1,
    paddingVertical: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  switchButtonActive: {
    backgroundColor: '#11D9EF',
  },
  switchButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  switchDivider: {
    width: 1,
    backgroundColor: '#000',
    height: '100%',
  },
  modalButton: {
    backgroundColor: '#28a745',
    paddingVertical: 12,
    paddingHorizontal: 120,
    borderRadius: 5,
    marginTop: 10,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalCloseButton: {
    backgroundColor: '#dc3545',
    paddingVertical: 12,
    paddingHorizontal: 118,
    borderRadius: 5,
    marginTop: 10,
  },
  modalCloseText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  productTileDetails: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  productListContainer: {
    maxHeight: 300,
    width: '100%',
    marginVertical: 10,
  },
  selectedProductTile: {
    borderColor: '#11D9EF',
    borderWidth: 2,
  }
});

export default styles;